version: '3.9'

services:
  main_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main_service_container
    command: python main.py
    volumes:
      - .:/app
    working_dir: /app

  procession_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procession_service_container
    command: python data_procession.py
    volumes:
      - .:/app
    working_dir: /app

  struct_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: struct_service_container
    command: python data_struct.py
    volumes:
      - .:/app
    working_dir: /app
